WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

WINDOW_CENTER_X = 640
WINDOW_CENTER_Y = 360

CAMERA_PAN_COEFF = 128
CAMERA_STARTING_ZOOM_FACTOR = 1.0
CAMERA_MAX_ZOOM_FACTOR = 15.0
CAMERA_MIN_ZOOM_FACTOR = 1.0
CAMERA_ZOOM_COEFF = 0.1

GRID_SIZE = 512
DOOR_OFFSET = 18

UP = 0
RIGHT = 1
DOWN = 2
LEFT = 3

GRID_WIDTH = 20
GRID_HEIGHT = 20

CHARACTER_SIZE = 150
AREA_TILE_SIZE = 16

GAME_LIST_PAGE_SIZE = 8

PLAYERS_PER_GAME = 6

BACKGROUND_GROUP = 0
ROOMS_GROUP = 1
CHARACTERS_AND_DOORS_GROUP = 2
HIGHLIGHTS_GROUP = 3

NUMBER_OF_GROUPS = 4
